version: "3"

services: 

    web:
        container_name: "fe"
        image: "rafa98/premileal-front"
        ports: 
            - "8080:8080"
        environment: 
            VUE_APP_BASE_API_URL: host.docker.internal/premileal/api
        depends_on: 
            - api

    api:
        container_name: "be"
        image: "rafa98/premileal-back"
        ports: 
            - "3000:3000"
        environment: 
            DB_HOST: database
            DB_USER: postgres            
            DB_PASS: 12345
            DB_PASSWORD: 12345
            DB_NAME: premilealOficial
        depends_on: 
            - database

    database: 
        image: "rafa98/premileal-database"        
        environment: 
            POSTGRES_PASSWORD: 12345
            POSTGRES_USER: postgres
            POSTGRES_DB: premilealOficial
            DB_NAME: premilealOficial
        ports: 
            - '5432:5432'
